server:
    port: 8112

spring:
    application:
        name: swil-file-processor

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8110/eureka/